{%set build = 0 %}
{%set version = '0.5.1' %}

package:
  name: scikit-cuda
  version: {{version}}

about:
  home: http://github.com/lebedov/scikit-cuda
  license: BSD License
  summary: "Python interface to GPU-powered libraries."

source:
  fn: scikit-cuda-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-cuda/scikit-cuda-{{version}}.tar.gz
  md5: 85799293d64886501e84c7b41a808fe2

requirements:
  build:
    - mako
    - 'numpy >=1.2.0'
    - 'pycuda >=2014.1'
    - 'pytest >=2'
    - python
    - setuptools

  run:
    - mako
    - 'numpy >=1.2.0'
    - 'pycuda >=2014.1'
    - python

build:
  number: {{build}}
  string: py{{py}}_{{build}}
  script:
    - python setup.py install
